ALTER TABLE app.package
    ADD COLUMN IF NOT EXISTS package_code VARCHAR(50),
    ADD COLUMN IF NOT EXISTS status VARCHAR(20),
    ADD COLUMN IF NOT EXISTS wood_type VARCHAR(255),
    ADD COLUMN IF NOT EXISTS thickness_mm INTEGER,
    ADD COLUMN IF NOT EXISTS width_mm INTEGER,
    ADD COLUMN IF NOT EXISTS length_mm INTEGER;
